### ISSUE TITLE
Ok buddy boi

### ISSUE THREAD

**Issue by JReverse** [jaqxues/SnipTools#1]
![image](https://user-images.githubusercontent.com/40630518/91922060-98bb1800-ec92-11ea-8abb-088f43cda5e8.png)

you realize this is github not malware hub mr hoffman

**Comment by jaqxues** [comment]
I was hoping for this issue being more interesting, instead I end up with issue #1 being about a joke in the Xposed Description.

It's open source, read the code. There are absolutely no malicious intentions, it only uses Xposed to hook into an App. Closing since useless.
